---

dist: xenial
language: python
python: 3.7.2
install:
 - pip install -r requirements_dev.txt
 - pip install -e .
script:
 - black hammerai/
 - pytest
 - pytest --cov=hammerai
after_success:
 - coveralls
